name: Lint

on:
  pull_request:

permissions:
  contents: read   

jobs:
  differential-shellcheck:
      runs-on: ubuntu-latest
      
      permissions:
        contents: read
        security-events: write

      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
            
        - name: Run shellcheck
          uses: redhat-plumbers-in-action/differential-shellcheck@v4
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
